# Production/Development mode.
DEV_MODE: true

# Silence warning messages. Useful for development when still messing around with stuff and to
# avoid getting spammed. Warning should be fixed though for a prod build.
IGNORE_WARNINGS: false

# Up to how many players can be playing at once.
MAX_PLAYERS: 1000

# How often to save the current state of logged in players to their account in the DB.
# State changes (glory/stat exp/inventory item/bank item/etc. modified) are done in memory and then
# saved to the DB every interval.
# If the server crashes between intervals, then players will lose any changes since their last save.
ACCOUNT_AUTO_SAVE_RATE: 15000

# Each game day is split up into an amount of sections, but the total length of a full day cycle
# is always the same regardless of the ratio between dawn/day/dusk/night.
FULL_DAY_DURATION_MINUTES: 24

# Prevents all spawner entities from spawning any other entities.
# Will make any dungeons that require key drops for locked doors impossible to complete.
DISABLE_SPAWNER_AREAS: false

# How long the player character name can be.
MAX_CHARACTER_DISPLAY_NAME_LENGTH: 20

# How long the player account username can be for new accounts.
MAX_ACCOUNT_USERNAME_LENGTH: 50

# The board (map) to spawn players onto.
# Must be an existing, permanent instance, not a dynamically added
# board like for dungeons, which are created on demand.
PLAYER_SPAWN_BOARD_NAME: overworld

# The entrance bounds to spawn players within.
# Must be found on the given board given for PLAYER_SPAWN_BOARD_NAME.
# Some common overworld spawn entrances:
# city-spawn (Default player spawn)
# test-island (Dev area for easy access to most things)
# mage-tower-library-stairs (Mage tower ground floor)
# portal-ring-druid-village (Next to the druid village)
# west-pyramid (West Pyramid dungeon entrance)
# blood-halls (Blood Halls dungeon entrance)
PLAYER_SPAWN_ENTRANCE_NAME: city-spawn

# How long between each time the player entity can move. (ms)
# Lower is less delay, so faster move speed.
PLAYER_MOVE_DELAY: 250

# How much glory a new player starts with.
PLAYER_STARTING_GLORY: 100

# How many hitpoints a player entity can have.
PLAYER_MAX_HITPOINTS: 200

# How much energy a player entity can have.
PLAYER_MAX_ENERGY: 20

# How long each energy point takes to regenerate. (ms)
PLAYER_ENERGY_REGEN_RATE: 1000

# How much to multiply the crafting bonus by.
# The crafting bonus is how much percent extra durability/quantity is added to crafted items, and
# is determined by the average of the players stats that are listed in the stats for the recipe.
# So if a recipe uses the stats Weaponry and Toolery, it will take the average of the player's
# Weaponry and Toolery stats and multiply that by this setting value.
# With an average stat level of 7 and with a crafting bonus multiplier of 2, the crafted item will
# have 14% more durability/quantity than its base amount.
CRAFTING_STAT_BONUS_MULTIPLIER: 1

# How much weight a player can carry at once.
MAX_INVENTORY_WEIGHT: 500

# How much to increase a player's max inventory weight by for each level they have gained in every stat.
# e.g. with this setting of 10, a base max inventory weight setting of 1000, and a player with 3
# stats of levels 4 (3), 11 (10), and 23 (22), then their max inventory weight would be 1350.
# Note that this is GAINED levels only, and doesn't include the base level of 1, so -1 from each stat.
# (3 + 10 + 22) * 10 = 350 + 1000 = 1350
ADDITIONAL_MAX_INVENTORY_WEIGHT_PER_STAT_LEVEL: 10

# How much weight a player can have in their bank at once.
MAX_BANK_WEIGHT: 1000

# How much to increase the player's max bank weight by for each upgrade they have bought.
ADDITIONAL_MAX_BANK_WEIGHT_PER_UPGRADE: 50

# How much to multiply the cost of the next max bank weight upgrade by.
# The base cost of each upgrade is the current max weight.
# e.g. with this setting of 2, and a current max bank weight of 1650, the cost to buy the next
# upgrade would be 3300.
# 1650 * 2 = 3300
MAX_BANK_WEIGHT_UPGRADE_COST_MULTIPLIER: 4

STARTER_INVENTORY_ITEMS:
  - itemName: IronSword
  - itemName: HealthPotion
    quantity: 4

STARTER_BANK_ITEMS:
  - itemName: IronHatchet
  - itemName: IronPickaxe

# How much glory it costs for a player to change their character display name.
DISPLAY_NAME_CHANGE_COST: 1000

# How much to change the price of an NPC shop item by each time it is bought, so it can become more
# expensive to buy if bought frequently. Cumulative. Slowly returns back to the base price for that
# item.
SHOP_PRICE_INCREASE_MULTIPLIER: 1.05

# The channels/categories of chat topics that players can send their messages in, with configurable
# cooldowns to limit the message rate of each player in that scope.
CHAT_SCOPES:
  LOCAL:
    value: LOCAL
    cooldown: 0
  GLOBAL:
    value: GLOBAL
    cooldown: 5000
  TRADE:
    value: TRADE
    cooldown: 5000

# How long incoming player chat messages can be.
MAX_CHAT_MESSAGE_LENGTH: 255

# How many seconds after receiving damage player in combat flag is true
IN_COMBAT_STATUS_DURATION: 15000
